---
version: "3.7"
services:
  db:
    image: postgres:11
    ports: ["54321:5432"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d